default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: jhoniersantan1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sismologia_app

test:
  <<: *default
  database: sismologia_app_test


production:
  <<: *default
  database: sismologia_app

